import {useEffect,useState} from 'react';import {ToolcraftButton as Button} from '@licketysplit/ui';import {useProjectStore} from '../../../stores/project-store';import {useSettingsStore} from '../../../stores/settings-store';import {useLicketyWorkflowStore} from '../../../stores/lickety-workflow-store';
export function TranscriptControls(){const project=useProjectStore(s=>s.project);const addSubtitle=useProjectStore(s=>s.addSubtitle);const workflow=useLicketyWorkflowStore();const [keyReady,setKeyReady]=useState<boolean|null>(null);const [approved,setApproved]=useState(false);const [mode,setMode]=useState<'mixed'|'isolated-stereo'>('mixed');const [selected,setSelected]=useState<string[]>(()=>project.timeline.tracks.filter(t=>t.role==='dialogue'&&!t.muted).map(t=>t.id));const [recoveryId,setRecoveryId]=useState('');const [localError,setLocalError]=useState('');
 useEffect(()=>{void window.licketysplit?.lickety?.assemblyKeyStatus().then(setKeyReady);},[]);
 useEffect(()=>{const job=useLicketyWorkflowStore.getState().jobs[project.id];if(job&&!['completed','failed','cancelled','submission-unknown'].includes(job.state))void useLicketyWorkflowStore.getState().resume(project);},[project.id]);
 const candidates=project.timeline.tracks.filter(t=>!t.muted&&t.clips.some(c=>{const m=project.mediaLibrary.items.find(m=>m.id===c.mediaId);return m&&m.type!=='image'&&m.metadata.hasAudio!==false;}));
 const doc=project.lickety?.transcript;const job=workflow.jobs[project.id];const start=()=>{setApproved(false);const frozen={...project,timeline:{...project.timeline,tracks:project.timeline.tracks.map(t=>({...t,role:selected.includes(t.id)?'dialogue' as const:t.role==='dialogue'?'general' as const:t.role}))}};const participants=mode==='isolated-stereo'?selected.map((id,i)=>({channel:(i+1) as 1|2,participantId:project.timeline.tracks.find(t=>t.id===id)!.name})):undefined;void workflow.start(frozen,{mode,participants});};
 const insertCaptions=async()=>{if(!doc)return;for(let i=0;i<doc.words.length;i+=5){const words=doc.words.slice(i,i+5);await addSubtitle({id:crypto.randomUUID(),startTime:words[0].startMs/1000,endTime:words.at(-1)!.endMs/1000,text:words.map(w=>w.text).join(' '),words:words.map(w=>({text:w.text,startTime:w.startMs/1000,endTime:w.endMs/1000}))});}};
 return <section className="space-y-3" aria-label="AssemblyAI transcript"><h3 className="text-sm font-semibold text-fg">AssemblyAI transcript</h3><p className="text-xs text-fg-2">Transcribe audible dialogue from this timeline. Imported SRT/VTT remains available in Subtitles.</p>
 {keyReady===false&&<Button label="Add AssemblyAI key" onClick={()=>useSettingsStore.getState().openSettings('api-keys')} variant="primary" size="sm"/>}
 <fieldset disabled={workflow.busy} className="space-y-2"><legend className="text-xs font-medium">Dialogue tracks to upload</legend>{candidates.map(t=><label key={t.id} className="flex min-h-9 items-center gap-2 text-xs"><input type="checkbox" checked={selected.includes(t.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,t.id]:s.filter(id=>id!==t.id))}/>{t.name}</label>)}<label className="block text-xs">Audio mapping<select aria-label="Audio mapping" value={mode} onChange={e=>setMode(e.target.value as typeof mode)} className="mt-1 w-full rounded border border-border bg-bg-1 p-2"><option value="mixed">Mixed dialogue with speaker diarization</option><option value="isolated-stereo">Two isolated microphones, channels 1 and 2</option></select></label>{mode==='isolated-stereo'&&<p className="text-xs text-fg-2">Select exactly two isolated microphone tracks. The selected order maps to channels 1 and 2; shared camera sound is not isolated.</p>}<label className="flex min-h-10 items-start gap-2 text-xs"><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>I approve uploading the selected dialogue to AssemblyAI and using transcription credits.</label><Button label="Transcribe current timeline" variant="primary" size="sm" isDisabled={!keyReady||!approved||!selected.length||(mode==='isolated-stereo'&&selected.length!==2)} onClick={start}/></fieldset>
 {workflow.busy&&<Button label="Cancel transcription" variant="secondary" size="sm" onClick={()=>void workflow.cancel(project.id)}/>}{job&&<p role="status" className="text-xs text-fg-2">Transcription: {job.state}</p>}{(workflow.error||localError)&&<p role="alert" className="text-xs text-fg-2">{workflow.error||localError}</p>}
 {job?.state==='submission-unknown'&&<div className="space-y-2"><p className="text-xs">No new submission will run. Find this job in AssemblyAI and attach its ID to resume the existing request.</p><label className="block text-xs">Existing AssemblyAI job ID<input className="mt-1 w-full rounded border border-border bg-bg-1 p-2" value={recoveryId} onChange={e=>setRecoveryId(e.target.value)}/></label><Button label="Reconcile existing job" size="sm" onClick={()=>{void window.licketysplit?.lickety?.reconcileTranscription(job.jobId,recoveryId).then(()=>workflow.resume(project)).catch(e=>setLocalError(e.message));}} isDisabled={!recoveryId}/></div>}
 {doc&&<div className="space-y-2"><p className="text-xs text-fg-2">{doc.words.length} timed words saved with this project.</p><Button label="Add captions from transcript" variant="secondary" size="sm" onClick={()=>void insertCaptions()}/></div>}</section>;
}
