import {getOriginalFadePhase} from "../audio/clip-fade-envelope";
import type {Project} from '../types/project';import type {AnalysisSnapshot,AssetIdentity,DialogueSpan} from './types';
export function canonicalJson(value:unknown):string {if(Array.isArray(value))return '['+value.map(canonicalJson).join(',')+']';if(value&&typeof value==='object')return '{'+Object.entries(value).filter(([,v])=>v!==undefined).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>JSON.stringify(k)+':'+canonicalJson(v)).join(',')+'}';return JSON.stringify(value);}
export async function revisionHash(value:unknown):Promise<string>{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonicalJson(value)));return Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('');}
export async function createAnalysisSnapshot(project:Project,assets:AssetIdentity[]):Promise<AnalysisSnapshot>{
 const dialogueTracks=project.timeline.tracks.filter(t=>t.role==='dialogue'&&!t.muted);const solo=project.timeline.tracks.some(t=>t.solo&&!t.muted);const tracks=dialogueTracks.filter(t=>!solo||t.solo);if(!tracks.length)throw new Error('Choose the audible dialogue tracks before transcription');const dialogue:DialogueSpan[]=[];const used=new Map<string,AssetIdentity>();
 for(const [channel,track]of tracks.entries())for(const clip of track.clips){if(clip.volume===0)continue;const media=project.mediaLibrary.items.find(m=>m.id===clip.mediaId);if(!media||media.metadata.hasAudio===false)continue;const asset=assets.find(a=>a.mediaId===clip.mediaId);if(!asset)throw new Error(`Relink original dialogue: ${media.name}`);if(clip.reversed||(clip.speed??1)!==1||clip.speedKeyframes?.length||clip.freezeFrames?.length)throw new Error('Transcription requires forward normal-speed dialogue or a rendered stem');used.set(asset.assetId,asset);dialogue.push({clipId:clip.id,mediaId:clip.mediaId,assetId:asset.assetId,trackId:track.id,timelineStartMs:Math.round(clip.startTime*1000),timelineEndMs:Math.round((clip.startTime+clip.duration)*1000),sourceInMs:Math.round(clip.inPoint*1000),channel:channel+1,participantId:track.name,render:{volume:clip.volume,audioTrackIndex:clip.audioTrackIndex??0,fade:clip.fade,fadeOffsetMs:getOriginalFadePhase(clip).offset*1000,fadeDurationMs:getOriginalFadePhase(clip).duration*1000,automation:clip.automation,effects:clip.audioEffects,clipDurationMs:Math.round(clip.duration*1000)}});}
 if(!dialogue.length)throw new Error('No audible dialogue is available');const context={schemaVersion:1 as const,projectId:project.id,durationMs:Math.round(project.timeline.duration*1000),frameRate:project.settings.frameRate,assets:[...used.values()].sort((a,b)=>a.assetId.localeCompare(b.assetId)),dialogue:dialogue.sort((a,b)=>a.timelineStartMs-b.timelineStartMs||a.trackId.localeCompare(b.trackId))};return {...context,revisionHash:await revisionHash(context)};
}
export async function fullEditRevision(project:Project):Promise<string>{return revisionHash({...project,modifiedAt:0,lickety:project.lickety?{words:project.lickety.words,transcript:project.lickety.transcript?{snapshotHash:project.lickety.transcript.snapshotHash,words:project.lickety.transcript.words}:undefined,cues:project.lickety.cues}:undefined,mediaLibrary:{items:project.mediaLibrary.items.map(item=>({id:item.id,metadata:item.metadata,identity:item.nativeSource?.identity,sourceFile:item.sourceFile}))}});}
