import {it,expect} from 'vitest';import {makeWorkflowFixture} from './test-fixtures';import {compileNarrative,sliceTimeline,projectTranscript} from './timeline-slicer';import type {TranscriptDocument,NarrativeProposal} from './types';
const doc:TranscriptDocument={schemaVersion:1,snapshotHash:'s',preparedAudioSha256:'audio',provider:'assemblyai',providerJobId:'job',words:[{id:'a',text:'first',startMs:1000,endMs:3400,confidence:.99},{id:'b',text:'second',startMs:11000,endMs:12400,confidence:.99}]};const proposal:NarrativeProposal={schemaVersion:1,snapshotHash:'s',excerpts:[{id:'b-first',firstWordId:'b',lastWordId:'b',reason:'hook'},{id:'a-last',firstWordId:'a',lastWordId:'a',reason:'body'}],protectedAfterWordIds:[],reviewNotes:[]};
it('reorders existing camera edits, linked audio and title without changing source identities',()=>{const p=makeWorkflowFixture();const before=JSON.stringify(p.timeline);const result=compileNarrative(p,doc,proposal);expect(result.project.id).not.toBe(p.id);expect(result.project.mediaLibrary.items[0]).toBe(p.mediaLibrary.items[0]);expect(result.project.timeline.tracks[0].clips[0].mediaId).toBe('cam-b');expect(result.project.timeline.tracks[1].clips.map(c=>c.inPoint)).toEqual([11,1]);expect(result.project.timeline.duration).toBeCloseTo(3.8);expect(result.project.textClips?.[0].startTime).toBeCloseTo(1.4);expect(result.words.map(w=>w.sourceWordId)).toEqual(['b','a']);expect(JSON.stringify(p.timeline)).toBe(before);});
it('preserves evaluated animation boundaries and supported effects',()=>{const p=makeWorkflowFixture();const clip=p.timeline.tracks[0].clips[0];const animated={...p,timeline:{...p.timeline,tracks:[{...p.timeline.tracks[0],clips:[{...clip,keyframes:[{id:'k0',time:0,property:'transform.opacity',value:0,easing:'linear' as const},{id:'k1',time:10,property:'transform.opacity',value:1,easing:'linear' as const}]}]},...p.timeline.tracks.slice(1)]}};const next=sliceTimeline(animated,[{id:'r',inMs:1000,outMs:3400}]);const c=next.timeline.tracks[0].clips[0];expect(c.keyframes.find(k=>k.time===0)?.value).toBeCloseTo(.1);expect(c.effects).toEqual(clip.effects);expect(c.transform.scale).toEqual(clip.transform.scale);});
it.each([24000/1001,30000/1001])('keeps integer splice frames at fractional rate %s',frameRate=>{const result=compileNarrative(makeWorkflowFixture({frameRate}),doc,proposal);expect(result.project.timeline.duration*frameRate).toBeCloseTo(Math.round(result.project.timeline.duration*frameRate),6);expect(result.words).toHaveLength(2);});
it('second Narrative sees only current occurrences, with original word provenance',()=>{const result=compileNarrative(makeWorkflowFixture(),doc,{...proposal,excerpts:[proposal.excerpts[1]]});const view=projectTranscript(doc,result.words,'draft');expect(view.words).toHaveLength(1);expect(view.words[0].sourceWordId).toBe('a');expect(view.derivedFromSnapshotHash).toBe('s');});
it('explains unsupported transformations and refuses word duplication',()=>{const p=makeWorkflowFixture();expect(()=>compileNarrative({...p,nestedInstances:[{} as never]},doc,proposal)).toThrow(/nested/i);expect(()=>compileNarrative(p,doc,{...proposal,excerpts:[proposal.excerpts[0],{...proposal.excerpts[0],id:'again'}]})).toThrow(/repeat|duplicate/);});
it('rebases fade phase separately from volume automation',()=>{const p=makeWorkflowFixture();const source={...p,timeline:{...p.timeline,tracks:p.timeline.tracks.map(t=>t.id==='Alice'?{...t,clips:t.clips.map(c=>({...c,fade:{fadeIn:10,fadeOut:0},automation:{volume:[{time:0,value:0},{time:10,value:1}]}}))}:t)}};const clip=sliceTimeline(source,[{id:'r',inMs:1000,outMs:3400}]).timeline.tracks[1].clips[0];expect(clip.metadata?.licketyAudioEnvelope).toEqual({offset:1,duration:20});expect(clip.automation?.volume?.[0].value).toBeCloseTo(.1);expect(clip.fade?.fadeIn).toBe(10);});
it('slices constant-speed original clips in source time without changing speed',()=>{const p=makeWorkflowFixture();const source={...p,timeline:{...p.timeline,tracks:p.timeline.tracks.map(t=>t.id==='Alice'?{...t,clips:t.clips.map(c=>({...c,startTime:0,duration:20,inPoint:4,outPoint:44,speed:2}))}:t)}};const clip=sliceTimeline(source,[{id:'r',inMs:1000,outMs:3000}]).timeline.tracks[1].clips[0];expect(clip).toMatchObject({startTime:0,duration:2,inPoint:6,outPoint:10,speed:2});});
