import {PreparedAudioStore} from "../lickety/prepared-audio";
import {NativeAudioAnalysis} from "../lickety/audio-analysis";
import {randomUUID} from "node:crypto";
import {app,protocol} from 'electron';import {createReadStream,promises as fs} from 'node:fs';import {Readable} from 'node:stream';import path from 'node:path';import os from 'node:os';import {z} from 'zod';
import {handle} from './index';import {CHANNELS} from '../../shared/channels';
import {ManagedAssetRegistry,boundedRange} from '../lickety/asset-registry';import {ManagedMediaJobs,HeavyJobQueue} from '../lickety/media-jobs';import {getResourceProfile} from '../lickety/resource-policy';
import {analysisSnapshotSchema,audioPreparationOptionsSchema} from '../../shared/ipc-contract';
export const heavyQueue=new HeavyJobQueue();let registry:ManagedAssetRegistry|undefined;let jobs:ManagedMediaJobs|undefined;const controllers=new Map<string,AbortController>();
export function getAssetRegistry(){return registry??=new ManagedAssetRegistry(path.join(app.getPath('userData'),'managed-media'));}
let preparedStore:PreparedAudioStore|undefined;
export function getPreparedAudioStore(){if(!preparedStore)preparedStore=new PreparedAudioStore(path.join(getAssetRegistry().cacheDir,"prepared-audio"),new NativeAudioAnalysis(getAssetRegistry(),heavyQueue));return preparedStore;}
export function installLicketyIpc(){const r=getAssetRegistry();jobs=new ManagedMediaJobs(r,heavyQueue);
 const audio=new NativeAudioAnalysis(r,heavyQueue);
 handle(CHANNELS.licketyPrepareAudio,z.object({snapshot:analysisSnapshotSchema,options:audioPreparationOptionsSchema,requestId:z.string()}),async args=>{const c=new AbortController();controllers.set(args.requestId,c);try{return await getPreparedAudioStore().prepare(args.snapshot,args.options,c.signal);}finally{controllers.delete(args.requestId);}});
 handle(CHANNELS.licketyAudioWindow,z.object({assetId:z.string(),trackIndex:z.number().int().nonnegative(),startMs:z.number().nonnegative(),durationMs:z.number().positive().max(10000),sampleRate:z.union([z.literal(1000),z.literal(16000),z.literal(48000)]),channels:z.union([z.literal(1),z.literal(2)]),requestId:z.string().optional()}),async args=>{const id=args.requestId??randomUUID();const controller=new AbortController();controllers.set(id,controller);try{return await audio.getNativeAudioWindow(args.assetId,args.trackIndex,args.startMs,args.durationMs,controller.signal,args.sampleRate,args.channels);}finally{controllers.delete(id);}});
 handle(CHANNELS.licketyResourceProfile,z.undefined(),()=>getResourceProfile(os.totalmem()));
 handle(CHANNELS.licketyRegisterAsset,z.object({mediaId:z.string().min(1),path:z.string().min(1),managed:z.boolean().optional()}),async args=>{let file=args.path;if(args.managed){const destination=path.join(r.cacheDir,'originals');await fs.mkdir(destination,{recursive:true});const target=path.join(destination,randomUUID()+path.extname(file));await fs.copyFile(file,target);file=target;}return r.registerOriginal(args.mediaId,file);});
 handle(CHANNELS.licketyFindAsset,z.object({mediaId:z.string()}),args=>r.findMedia(args.mediaId));
 handle(CHANNELS.licketyResolve,z.object({assetId:z.string(),purpose:z.enum(['original','proxy'])}),async args=>{await r.resolve(args.assetId,args.purpose);return `licketysplit-media://${args.assetId}/${args.purpose}`;});
 handle(CHANNELS.licketyEnsureProxy,z.object({assetId:z.string()}),async args=>{const controller=new AbortController();controllers.set(args.assetId,controller);try{return await jobs!.ensureProxy(args.assetId,getResourceProfile(os.totalmem()),controller.signal);}finally{controllers.delete(args.assetId);}});
 handle(CHANNELS.licketyCancelMedia,z.object({assetId:z.string()}),args=>{controllers.get(args.assetId)?.abort(new Error('Media preparation cancelled'));});
 protocol.handle('licketysplit-media',async request=>{let size=0;try{const url=new URL(request.url);if(!/^[a-f0-9-]{36}$/.test(url.hostname)||!/^\/(original|proxy)$/.test(url.pathname)||url.search)throw new Error('Invalid asset URI');const resolved=await r.resolve(url.hostname,url.pathname.slice(1) as 'original'|'proxy');size=(await fs.stat(resolved.path)).size;const range=boundedRange(request.headers.get('Range'),size);const stream=createReadStream(resolved.path,{start:range.start,end:range.end,highWaterMark:1024*1024,signal:request.signal});const headers:Record<string,string>={'Content-Type':resolved.mime,'Accept-Ranges':'bytes','Content-Length':String(range.end-range.start+1),'Cross-Origin-Resource-Policy':'cross-origin','Access-Control-Allow-Origin':'app://openreel'};if(range.partial)headers['Content-Range']=`bytes ${range.start}-${range.end}/${size}`;return new Response(Readable.toWeb(stream) as ReadableStream,{status:range.partial?206:200,headers});}catch(e){return new Response('Managed media unavailable; relink or retry preparation',{status:size?416:404,headers:size?{'Content-Range':`bytes */${size}`}:{}});}});
}
