export const CHANNELS = {
  licketyReconcileTranscription:"licketysplit:lickety:reconcileTranscription",
  licketyKeyStatus:"licketysplit:lickety:keyStatus",
  licketyStartTranscription:"licketysplit:lickety:startTranscription",
  licketyGetTranscription:"licketysplit:lickety:getTranscription",
  licketyCancelTranscription:"licketysplit:lickety:cancelTranscription",
  licketyResumeTranscription:"licketysplit:lickety:resumeTranscription",
  licketyPrepareAudio:"licketysplit:lickety:prepareAudio",
  licketyAudioWindow: "licketysplit:lickety:audioWindow",
  licketyResourceProfile: "licketysplit:lickety:resourceProfile",
  licketyReferenceOriginal: "licketysplit:lickety:referenceOriginal",
  licketyOriginalUri: "licketysplit:lickety:originalUri",
  licketyRegisterAsset: "licketysplit:lickety:registerAsset",
  licketyFindAsset: "licketysplit:lickety:findAsset",
  licketyResolve: "licketysplit:lickety:resolve",
  licketyEnsureAudioStream: "licketysplit:lickety:ensureAudioStream",
  licketyEnsureProxy: "licketysplit:lickety:ensureProxy",
  licketyCancelMedia: "licketysplit:lickety:cancelMedia",
  licketyIdentifyOriginal: "licketysplit:lickety:identifyOriginal",
  licketyFindOriginalMediaId: "licketysplit:lickety:findOriginalMediaId",
  podcastInspect: "licketysplit:podcast:inspect",
  podcastRevise: "licketysplit:podcast:revise",
  podcastAnalyze: "licketysplit:podcast:analyze",
  podcastUpdate: "licketysplit:podcast:update",
  podcastGet: "licketysplit:podcast:get",
  podcastWaveform: "licketysplit:podcast:waveform",
  podcastCancel: "licketysplit:podcast:cancel",
  podcastApprove: "licketysplit:podcast:approve",
  podcastProgress: "licketysplit:podcast:progress",
  probeHardware: "licketysplit:probeHardware",
  fsShowSaveDialog: "licketysplit:fs:showSaveDialog",
  fsShowOpenDialog: "licketysplit:fs:showOpenDialog",
  fsReadFile: "licketysplit:fs:readFile",
  fsWriteFile: "licketysplit:fs:writeFile",
  fsOpenWrite: "licketysplit:fs:openWrite",
  fsWriteChunk: "licketysplit:fs:writeChunk",
  fsCloseWrite: "licketysplit:fs:closeWrite",
  fsAbortWrite: "licketysplit:fs:abortWrite",
  fsRevealInFolder: "licketysplit:fs:revealInFolder",
  fsReadFileBytes: "licketysplit:fs:readFileBytes",
  fsTempFilePath: "licketysplit:fs:tempFilePath",
  keychainGet: "licketysplit:keychain:get",
  keychainSet: "licketysplit:keychain:set",
  keychainDelete: "licketysplit:keychain:delete",
  exportStart: "licketysplit:export:start",
  exportWriteAudioWav: "licketysplit:export:writeAudioWav",
  exportWriteAudioChunk: "licketysplit:export:writeAudioChunk",
  exportFinishAudio: "licketysplit:export:finishAudio",
  exportCancel: "licketysplit:export:cancel",
  auroraRenderPreview: "licketysplit:aurora:renderPreview",
  auroraStartPreviewSession: "licketysplit:aurora:startPreviewSession",
  auroraCancelPreviewSession: "licketysplit:aurora:cancelPreviewSession",
  auroraPreviewEvent: "licketysplit:aurora:previewEvent",
  auroraStartSequenceSession: "licketysplit:aurora:startSequenceSession",
  auroraCancelSequenceSession: "licketysplit:aurora:cancelSequenceSession",
  auroraSequenceEvent: "licketysplit:aurora:sequenceEvent",
  mediaGenerateProxy: "licketysplit:media:generateProxy",
  mediaTranscode: "licketysplit:media:transcode",
  mediaExtractAudioWav: "licketysplit:media:extractAudioWav",
  mediaInspectOriginal: "licketysplit:media:inspectOriginal",
  mediaProbeAudioStreams: "licketysplit:media:probeAudioStreams",
  mediaFetchUrl: "licketysplit:media:fetchUrl",
  riggingProbeBackend: "licketysplit:rigging:probeBackend",
  riggingRigHumanoidModel: "licketysplit:rigging:rigHumanoidModel",
  cloudFetch: "licketysplit:cloud:fetch",
  windowControl: "licketysplit:window:control",
  windowIsMaximized: "licketysplit:window:isMaximized",
  lifecycleUnsavedQuery: "licketysplit:lifecycle:unsavedQuery",
  lifecycleUnsavedReply: "licketysplit:lifecycle:unsavedReply",
  lifecycleFlush: "licketysplit:lifecycle:flush",
  lifecycleFlushed: "licketysplit:lifecycle:flushed",
  updaterStatus: "licketysplit:updater:status",
  updaterDownload: "licketysplit:updater:download",
  updaterInstall: "licketysplit:updater:install",
  crashReport: "licketysplit:crash:report",
  mcpRequest: "licketysplit:mcp:request",
  mcpResponse: "licketysplit:mcp:response",
  mcpGetStatus: "licketysplit:mcp:getStatus",
  mcpRotateToken: "licketysplit:mcp:rotateToken",
  mcpTestConnection: "licketysplit:mcp:testConnection",
} as const;
