export const CHANNELS = {
  licketyReconcileTranscription:"openreel:lickety:reconcileTranscription",
  licketyKeyStatus:"openreel:lickety:keyStatus",
  licketyStartTranscription:"openreel:lickety:startTranscription",
  licketyGetTranscription:"openreel:lickety:getTranscription",
  licketyCancelTranscription:"openreel:lickety:cancelTranscription",
  licketyResumeTranscription:"openreel:lickety:resumeTranscription",
  licketyPrepareAudio:"openreel:lickety:prepareAudio",
  licketyAudioWindow: "openreel:lickety:audioWindow",
  licketyResourceProfile: "openreel:lickety:resourceProfile",
  licketyReferenceOriginal: "openreel:lickety:referenceOriginal",
  licketyOriginalUri: "openreel:lickety:originalUri",
  licketyRegisterAsset: "openreel:lickety:registerAsset",
  licketyFindAsset: "openreel:lickety:findAsset",
  licketyResolve: "openreel:lickety:resolve",
  licketyEnsureAudioStream: "openreel:lickety:ensureAudioStream",
  licketyEnsureProxy: "openreel:lickety:ensureProxy",
  licketyCancelMedia: "openreel:lickety:cancelMedia",
  probeHardware: "openreel:probeHardware",
  fsShowSaveDialog: "openreel:fs:showSaveDialog",
  fsShowOpenDialog: "openreel:fs:showOpenDialog",
  fsReadFile: "openreel:fs:readFile",
  fsWriteFile: "openreel:fs:writeFile",
  fsOpenWrite: "openreel:fs:openWrite",
  fsWriteChunk: "openreel:fs:writeChunk",
  fsCloseWrite: "openreel:fs:closeWrite",
  fsAbortWrite: "openreel:fs:abortWrite",
  fsRevealInFolder: "openreel:fs:revealInFolder",
  fsReadFileBytes: "openreel:fs:readFileBytes",
  fsTempFilePath: "openreel:fs:tempFilePath",
  keychainGet: "openreel:keychain:get",
  keychainSet: "openreel:keychain:set",
  keychainDelete: "openreel:keychain:delete",
  exportStart: "openreel:export:start",
  exportWriteAudioWav: "openreel:export:writeAudioWav",
  exportWriteAudioChunk: "openreel:export:writeAudioChunk",
  exportFinishAudio: "openreel:export:finishAudio",
  exportCancel: "openreel:export:cancel",
  auroraRenderPreview: "openreel:aurora:renderPreview",
  auroraStartPreviewSession: "openreel:aurora:startPreviewSession",
  auroraCancelPreviewSession: "openreel:aurora:cancelPreviewSession",
  auroraPreviewEvent: "openreel:aurora:previewEvent",
  auroraStartSequenceSession: "openreel:aurora:startSequenceSession",
  auroraCancelSequenceSession: "openreel:aurora:cancelSequenceSession",
  auroraSequenceEvent: "openreel:aurora:sequenceEvent",
  mediaGenerateProxy: "openreel:media:generateProxy",
  mediaTranscode: "openreel:media:transcode",
  mediaExtractAudioWav: "openreel:media:extractAudioWav",
  mediaInspectOriginal: "openreel:media:inspectOriginal",
  mediaProbeAudioStreams: "openreel:media:probeAudioStreams",
  mediaFetchUrl: "openreel:media:fetchUrl",
  riggingProbeBackend: "openreel:rigging:probeBackend",
  riggingRigHumanoidModel: "openreel:rigging:rigHumanoidModel",
  cloudFetch: "openreel:cloud:fetch",
  windowControl: "openreel:window:control",
  windowIsMaximized: "openreel:window:isMaximized",
  lifecycleUnsavedQuery: "openreel:lifecycle:unsavedQuery",
  lifecycleUnsavedReply: "openreel:lifecycle:unsavedReply",
  lifecycleFlush: "openreel:lifecycle:flush",
  lifecycleFlushed: "openreel:lifecycle:flushed",
  updaterStatus: "openreel:updater:status",
  updaterDownload: "openreel:updater:download",
  updaterInstall: "openreel:updater:install",
  crashReport: "openreel:crash:report",
  mcpRequest: "openreel:mcp:request",
  mcpResponse: "openreel:mcp:response",
  mcpGetStatus: "openreel:mcp:getStatus",
  mcpRotateToken: "openreel:mcp:rotateToken",
  mcpTestConnection: "openreel:mcp:testConnection",
} as const;
