import {createReadStream} from 'node:fs';import {Readable} from 'node:stream';
export class AssemblyAIHttpError extends Error{constructor(readonly status:number,readonly retryAfterMs=0){super(`AssemblyAI HTTP ${status}`);}}
export type AssemblyAITransport=(url:string,options:RequestInit&{duplex?:'half'})=>Promise<Response>;
export class AssemblyAIClient {
 constructor(private transport:AssemblyAITransport=(url,options)=>fetch(url,options),private speechModels=['universal-2']){}
 private async request(route:string,key:string,options:RequestInit&{duplex?:'half'}):Promise<Record<string,unknown>>{const response=await this.transport('https://api.assemblyai.com/v2/'+route,{...options,headers:{...options.headers,authorization:key}});if(!response.ok){const retry=response.headers.get('Retry-After');const seconds=Number(retry);const delay=retry?Number.isFinite(seconds)?seconds*1000:Math.max(0,Date.parse(retry)-Date.now()):0;throw new AssemblyAIHttpError(response.status,delay);}const result=await response.json();if(!result||typeof result!=='object')throw new Error('Invalid AssemblyAI response');return result as Record<string,unknown>;}
 async upload(file:string,key:string,signal:AbortSignal):Promise<string>{const body=Readable.toWeb(createReadStream(file,{highWaterMark:1024*1024,signal})) as unknown as BodyInit;const raw=await this.request('upload',key,{method:'POST',headers:{'Content-Type':'application/octet-stream'},body,duplex:'half',signal});if(typeof raw.upload_url!=='string'||!raw.upload_url.startsWith('https://'))throw new Error('Invalid AssemblyAI upload acknowledgement');return raw.upload_url;}
 async submit(audioUrl:string,key:string,mode:'mixed'|'isolated-stereo',signal:AbortSignal):Promise<string>{const raw=await this.request('transcript',key,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({audio_url:audioUrl,speech_models:this.speechModels,multichannel:mode==='isolated-stereo',speaker_labels:mode==='mixed'}),signal});if(typeof raw.id!=='string'||!raw.id)throw new Error('Invalid AssemblyAI submission acknowledgement');return raw.id;}
 async poll(providerJobId:string,key:string,signal:AbortSignal):Promise<Record<string,unknown>>{return this.request('transcript/'+encodeURIComponent(providerJobId),key,{method:'GET',signal});}
}
