import {createReadStream} from 'node:fs';
import {promises as fs} from 'node:fs';
import path from 'node:path'; import {createHash,randomUUID} from 'node:crypto';
import type {RegisteredAsset,ProxyReceipt} from '../../../../../packages/core/src/lickety/types';
interface RecordEntry {asset:RegisteredAsset;path:string;fingerprint:string;proxyPath?:string;receipt?:ProxyReceipt;audioPreviews?:Record<string,string>;}
export async function hashFile(file:string,signal?:AbortSignal):Promise<string>{const hash=createHash('sha256');for await(const chunk of createReadStream(file,{highWaterMark:1024*1024,signal})){signal?.throwIfAborted();hash.update(chunk);}return hash.digest('hex');}
export async function atomicJson(file:string,value:unknown):Promise<void>{await fs.mkdir(path.dirname(file),{recursive:true});const temp=file+'.'+randomUUID()+'.tmp';await fs.writeFile(temp,JSON.stringify(value),{mode:0o600});await fs.rename(temp,file);}
export function boundedRange(header:string|null,size:number):{start:number;end:number;partial:boolean}{if(size<=0)throw new Error('Empty asset');if(!header)return {start:0,end:size-1,partial:false};const m=/^bytes=(\d*)-(\d*)$/.exec(header);if(!m||(!m[1]&&!m[2]))throw new Error('Invalid byte range');let start=m[1]?Number(m[1]):Math.max(0,size-Number(m[2]));let end=m[1]&&m[2]?Number(m[2]):size-1;if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start>=size||end<start)throw new Error('Unsatisfiable byte range');end=Math.min(end,size-1,start+16*1024**2-1);return {start,end,partial:true};}
export class ManagedAssetRegistry {
 readonly cacheDir:string;private records=new Map<string,RecordEntry>();private loaded=false;private pins=new Set<string>();private mutation:Promise<unknown>=Promise.resolve();
 constructor(cacheDir:string){this.cacheDir=path.resolve(cacheDir);}
 private async load(){if(this.loaded)return;await fs.mkdir(this.cacheDir,{recursive:true});try{const rows=JSON.parse(await fs.readFile(path.join(this.cacheDir,'assets.json'),'utf8')) as RecordEntry[];for(const r of rows)if(/^[a-f0-9-]{36}$/.test(r.asset.identity.assetId))this.records.set(r.asset.identity.assetId,r);}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}this.loaded=true;}
 private async save(){await atomicJson(path.join(this.cacheDir,'assets.json'),[...this.records.values()]);}
 async registerOriginal(mediaId:string,file:string,signal?:AbortSignal):Promise<RegisteredAsset>{const work=this.mutation.catch(()=>{}).then(()=>this.register(mediaId,file,signal));this.mutation=work;return work;}
 private async register(mediaId:string,file:string,signal?:AbortSignal):Promise<RegisteredAsset>{await this.load();signal?.throwIfAborted();const resolved=await fs.realpath(file);const stat=await fs.stat(resolved);if(!stat.isFile())throw new Error('Original must be a file');for(const r of this.records.values())if(r.path===resolved&&r.asset.identity.mediaId===mediaId&&r.fingerprint===`${stat.size}:${stat.mtimeMs}`)return r.asset;const sha256=await hashFile(resolved,signal);for(const r of this.records.values())if(r.path===resolved&&r.asset.identity.mediaId===mediaId&&r.asset.identity.sha256===sha256)return r.asset;const assetId=randomUUID();const asset:RegisteredAsset={identity:{assetId,mediaId,sha256,byteLength:stat.size},originalUri:`licketysplit-media://${assetId}/original`,durationMs:0};this.records.set(assetId,{asset,path:resolved,fingerprint:`${stat.size}:${stat.mtimeMs}`});await this.save();return asset;}
 async get(assetId:string):Promise<RegisteredAsset>{await this.load();const r=this.records.get(assetId);if(!r)throw new Error('Unknown managed asset; relink original');return r.asset;}
 async findMedia(mediaId:string):Promise<RegisteredAsset|undefined>{await this.load();return [...this.records.values()].reverse().find(r=>r.asset.identity.mediaId===mediaId)?.asset;}
 async resolve(assetId:string,purpose:'original'|'proxy'):Promise<{path:string;mime:string}>{await this.load();const r=this.records.get(assetId);if(!r)throw new Error('Unknown managed asset; relink original');let stat;try{stat=await fs.stat(r.path);}catch{throw new Error('Original unavailable; relink the original recording');}if(`${stat.size}:${stat.mtimeMs}`!==r.fingerprint){if(await hashFile(r.path)!==r.asset.identity.sha256)throw new Error('Original changed; relink and prepare media again');r.fingerprint=`${stat.size}:${stat.mtimeMs}`;}if(purpose==='original')return {path:r.path,mime:mimeFor(r.path)};if(!r.proxyPath||!r.receipt||r.receipt.sourceSha256!==r.asset.identity.sha256)throw new Error('Preview proxy is not ready; retry preparation');await fs.access(r.proxyPath);this.pins.add(assetId);return {path:r.proxyPath,mime:'video/mp4'};}
 async receipt(assetId:string):Promise<ProxyReceipt|undefined>{await this.load();const r=this.records.get(assetId);if(!r?.receipt)return;try{await this.resolve(assetId,'proxy');return r.receipt;}catch{return;}}
 async audioPreview(assetId:string,index:number):Promise<{path:string;mime:string}|undefined>{await this.resolve(assetId,'original');const r=this.records.get(assetId)!;const file=r.audioPreviews?.[String(index)];if(!file)return;try{await fs.access(file);return {path:file,mime:'audio/mp4'};}catch{return;}}
 async promoteAudioPreview(assetId:string,index:number,file:string){await this.load();const r=this.records.get(assetId);if(!r)throw new Error('Unknown asset');const rel=path.relative(this.cacheDir,path.resolve(file));if(rel.startsWith('..')||path.isAbsolute(rel))throw new Error('Derivative must be inside managed cache');r.audioPreviews??={};r.audioPreviews[String(index)]=file;await this.save();}
 async trimDerivedCache(extraBytes:number,protectedAsset:string,cap=10*1024**3){
  await this.load();const rows:Array<{id:string;file:string;size:number;time:number;remove:()=>void}>=[];let total=extraBytes;
  for(const [id,r]of this.records){const files:[string,()=>void][]=[];if(r.proxyPath)files.push([r.proxyPath,()=>{delete r.proxyPath;delete r.receipt;}]);for(const [index,file]of Object.entries(r.audioPreviews??{}))files.push([file,()=>{delete r.audioPreviews![index];}]);for(const [file,remove]of files){const stat=await fs.stat(file).catch(()=>undefined);if(stat){total+=stat.size;rows.push({id,file,size:stat.size,time:stat.mtimeMs,remove});}}}
  for(const row of rows.sort((a,b)=>a.time-b.time)){if(total<=cap)break;if(row.id===protectedAsset||this.pins.has(row.id))continue;const rel=path.relative(this.cacheDir,row.file);if(rel.startsWith('..')||path.isAbsolute(rel)||row.file.includes(path.sep+'originals'+path.sep))throw new Error('Invalid derivative cache entry');await fs.unlink(row.file);row.remove();total-=row.size;}await this.save();if(total>cap)throw new Error('Managed preview cache cap reached by active files; close this project or increase cache limit');
 }
 async promoteProxy(assetId:string,file:string,receipt:ProxyReceipt){await this.load();const r=this.records.get(assetId);if(!r)throw new Error('Unknown asset');const rel=path.relative(this.cacheDir,path.resolve(file));if(rel.startsWith('..')||path.isAbsolute(rel))throw new Error('Derivative must be inside managed cache');r.proxyPath=file;r.receipt=receipt;this.pins.add(assetId);await this.save();}
}
function mimeFor(file:string){const ext=path.extname(file).toLowerCase();return ({'.mp4':'video/mp4','.mov':'video/quicktime','.webm':'video/webm','.wav':'audio/wav','.mp3':'audio/mpeg','.m4a':'audio/mp4'} as Record<string,string>)[ext]??'application/octet-stream';}
