import {promises as fs} from 'node:fs';import path from 'node:path';import {randomUUID} from 'node:crypto';
import type {AnalysisSnapshot,PreparedAudio,TranscriptDocument,JobState} from '../../../../../packages/core/src/lickety/types';import {normalizeAssemblyTranscript} from '../../../../../packages/core/src/lickety/transcript';import {atomicJson} from './asset-registry';import {AssemblyAIHttpError} from './assemblyai-client';
export interface TranscriptionArguments {audio:PreparedAudio;snapshot:AnalysisSnapshot;mode:'mixed'|'isolated-stereo';participants?:{channel:1|2;participantId:string}[];confirmationId:string;}
export interface TranscriptionJob extends TranscriptionArguments {id:string;state:JobState;providerJobId?:string;providerUploadUrl?:string;transcript?:TranscriptDocument;error?:string;}
export class JobStore {
 constructor(private directory:string){}
 private file(id:string){if(!/^[a-zA-Z0-9-]+$/.test(id))throw new Error('Unknown transcription job');return path.join(this.directory,id+'.json');}
 async write(job:TranscriptionJob){await atomicJson(this.file(job.id),job);}
 async read(id:string):Promise<TranscriptionJob>{return JSON.parse(await fs.readFile(this.file(id),'utf8')) as TranscriptionJob;}
 async list():Promise<TranscriptionJob[]>{await fs.mkdir(this.directory,{recursive:true});const jobs:TranscriptionJob[]=[];for(const name of await fs.readdir(this.directory))if(name.endsWith('.json'))jobs.push(await this.read(name.slice(0,-5)));return jobs;}
}
interface Provider {upload(file:string,key:string,signal:AbortSignal):Promise<string>;submit(url:string,key:string,mode:'mixed'|'isolated-stereo',signal:AbortSignal):Promise<string>;poll(id:string,key:string,signal:AbortSignal):Promise<Record<string,unknown>>;}
const wait=(ms:number,signal:AbortSignal)=>new Promise<void>((resolve,reject)=>{signal.throwIfAborted();const timer=setTimeout(()=>{signal.removeEventListener('abort',abort);resolve();},ms);const abort=()=>{clearTimeout(timer);reject(signal.reason);};signal.addEventListener('abort',abort,{once:true});});
export class TranscriptionJobs {
 private running=new Map<string,AbortController>();private live=new Map<string,TranscriptionJob>();private pendingSubmissions=new Set<string>();
 constructor(private store:JobStore,private audio:{resolve(audio:PreparedAudio):Promise<string>},private provider:Provider,private key:()=>Promise<string|null>,private delay=wait){}
 async startTranscription(args:TranscriptionArguments):Promise<{jobId:string}>{if(!args.confirmationId)throw new Error('Confirm the paid transcription action');if(args.audio.snapshotHash!==args.snapshot.revisionHash)throw new Error('Stale prepared audio');const all=await this.store.list();const cached=all.find(job=>(job.confirmationId===args.confirmationId||((job.state==='completed'||(job.providerJobId&&job.state!=='failed'))&&job.audio.sha256===args.audio.sha256&&job.snapshot.revisionHash===args.snapshot.revisionHash&&job.mode===args.mode&&JSON.stringify(job.participants)===JSON.stringify(args.participants))));if(cached){if(cached.state!=='completed')await this.resumeTranscription(cached.id);return {jobId:cached.id};}if(all.some(job=>job.state==='submission-unknown'&&job.audio.sha256===args.audio.sha256))throw new Error('Reconcile the uncertain provider submission before any new paid action');if(!await this.key())throw new Error('AssemblyAI key is missing or OS key storage is locked');await this.audio.resolve(args.audio);const job:TranscriptionJob={...args,id:randomUUID(),state:'queued'};await this.save(job);this.launch(job);return {jobId:job.id};}
 private async save(job:TranscriptionJob){this.live.set(job.id,{...job});await this.store.write(job);}
 private launch(job:TranscriptionJob){if(this.running.has(job.id))return;const c=new AbortController();this.running.set(job.id,c);void this.run(job,c.signal).finally(()=>this.running.delete(job.id)).catch(()=>{});}
 async getTranscription(id:string):Promise<{state:JobState;providerJobId?:string;transcript?:TranscriptDocument;error?:string}>{const job=this.live.get(id)??await this.store.read(id);return {state:this.pendingSubmissions.has(id)?"submitted":job.state,providerJobId:job.providerJobId,transcript:job.transcript,error:job.error};}
 async cancelTranscription(id:string){const job=this.live.get(id)??await this.store.read(id);if(job.state==='completed')return;this.running.get(id)?.abort(new Error('Cancelled'));job.state=this.pendingSubmissions.has(id)?'submission-unknown':'cancelled';job.error=job.providerJobId?'Local polling stopped. The submitted provider job may continue.':'Local transcription cancelled before provider submission.';await this.save(job);}
 async resumeTranscription(id:string){const job=await this.store.read(id);if(job.state==='completed'||job.state==='submission-unknown')return;if(job.providerJobId){job.state='submitted';job.error=undefined;await this.save(job);this.launch(job);}else if(['queued','preparing','uploading'].includes(job.state))this.launch(job);}
 async reconcileTranscription(id:string,providerJobId:string){const job=await this.store.read(id);if(job.state!=="submission-unknown"||!job.providerUploadUrl)throw new Error("No uncertain provider submission to reconcile");const key=await this.key();if(!key)throw new Error("AssemblyAI key unavailable");const raw=await this.provider.poll(providerJobId,key,new AbortController().signal);if(raw.audio_url!==job.providerUploadUrl)throw new Error("Provider job does not match the submitted audio; do not attach it");job.providerJobId=providerJobId;job.state="submitted";job.error=undefined;await this.save(job);this.launch(job);}
 async resumeKnownJobs(){for(const job of await this.store.list())if(job.providerJobId&&['submitted','processing'].includes(job.state))await this.resumeTranscription(job.id);}
 private async run(job:TranscriptionJob,signal:AbortSignal){let posted=false;try{const key=await this.key();if(!key)throw new Error('missing-key');if(!job.providerJobId){job.state='uploading';await this.save(job);const file=await this.audio.resolve(job.audio);const url=await this.provider.upload(file,key,signal);signal.throwIfAborted();job.providerUploadUrl=url;job.state='submission-unknown';job.error='Awaiting provider acknowledgement. Do not submit this audio again.';await this.save(job);posted=true;this.pendingSubmissions.add(job.id);job.providerJobId=await this.provider.submit(url,key,job.mode,signal);job.state='submitted';job.error=undefined;await this.save(job);this.pendingSubmissions.delete(job.id);}
 for(;;){signal.throwIfAborted();let raw:Record<string,unknown>|undefined;for(let attempt=0;attempt<=3;attempt++){try{raw=await this.provider.poll(job.providerJobId!,key,signal);break;}catch(error){signal.throwIfAborted();if(attempt===3||(error instanceof AssemblyAIHttpError&&error.status!==429&&error.status<500))throw error;await this.delay(error instanceof AssemblyAIHttpError?Math.min(60000,Math.max(1000*2**attempt,error.retryAfterMs)):1000*2**attempt,signal);}}
 if(raw?.status==='completed'){job.transcript=normalizeAssemblyTranscript(raw,job.snapshot,job.audio,job.participants);job.state='completed';job.error=undefined;await this.save(job);return;}if(raw?.status==='error')throw new Error('provider-failed');if(raw?.status!=='queued'&&raw?.status!=='processing')throw new Error('Invalid provider job status');job.state='processing';await this.save(job);await this.delay(3000,signal);}
 }catch(error){this.pendingSubmissions.delete(job.id);if(signal.aborted&&posted&&!job.providerJobId){job.state='submission-unknown';job.error='Cancelled while awaiting submission acknowledgement. Reconcile the provider before any new paid submission.';}else if(signal.aborted){job.state='cancelled';job.error=job.providerJobId?'Local work cancelled; the submitted provider job may continue.':'Local work cancelled.';}else if(posted&&!job.providerJobId&&!(error instanceof AssemblyAIHttpError)){job.state='submission-unknown';job.error='Submission acknowledgement lost. Reconcile the provider job before any new paid submission.';}else{job.state='failed';job.error=error instanceof AssemblyAIHttpError?error.message:'AssemblyAI job failed; check credentials, source audio and provider status before retrying.';}await this.save(job).catch(()=>{});}}
}
