import {promises as fs} from 'node:fs';import path from 'node:path';import {spawn} from 'node:child_process';
import type {ResourceProfile,ProxyReceipt} from '../../../../../packages/core/src/lickety/types';
import {ManagedAssetRegistry} from './asset-registry';
export class HeavyJobQueue {
 private tail:Promise<unknown>=Promise.resolve();
 async run<T>(work:()=>Promise<T>,signal:AbortSignal):Promise<T>{
  signal.throwIfAborted();let release!:()=>void;const next=new Promise<void>(r=>release=r);const prev=this.tail;this.tail=prev.catch(()=>{}).then(()=>next);
  let abort!:()=>void;const cancelled=new Promise<never>((_,reject)=>{abort=()=>reject(signal.reason);signal.addEventListener('abort',abort,{once:true});});
  try{await Promise.race([prev.catch(()=>{}),cancelled]);signal.removeEventListener('abort',abort);signal.throwIfAborted();return await work();}finally{signal.removeEventListener('abort',abort);release();}
 }
}
export const heavyQueue = new HeavyJobQueue();
export function proxyDimensions(width:number,height:number){if(!(width>0&&height>0))throw new Error('Invalid video dimensions');const scale=Math.min(1,960/Math.max(width,height),540/Math.min(width,height));return {width:Math.max(2,Math.floor(width*scale/2)*2),height:Math.max(2,Math.floor(height*scale/2)*2)};}
export async function runFfmpeg(args:string[],signal:AbortSignal):Promise<string>{const {resolveFfmpegPath}=await import('../sidecar/ffmpeg-path');return runProcess(resolveFfmpegPath(),args,signal);}
export async function runProcess(binary:string,args:string[],signal:AbortSignal):Promise<string>{signal.throwIfAborted();return new Promise((resolve,reject)=>{const child=spawn(binary,args,{stdio:['ignore','ignore','pipe']});let stderr='';const abort=()=>child.kill('SIGKILL');signal.addEventListener('abort',abort,{once:true});child.stderr.on('data',b=>{stderr=(stderr+b.toString()).slice(-32768);});child.once('error',reject);child.once('close',code=>{signal.removeEventListener('abort',abort);if(signal.aborted)reject(signal.reason);else if(code===0)resolve(stderr);else reject(new Error(`Media processing failed (${code}): ${stderr.slice(-2000)}`));});});}
export interface VideoProbe {width:number;height:number;durationMs:number;startPTS:number;}
export async function probeVideo(file:string,signal:AbortSignal):Promise<VideoProbe>{signal.throwIfAborted();const {probeInputHeader}=await import('../sidecar/probe-streams');const {parseOriginalMetadata}=await import('./import-inspection');const output=await probeInputHeader(file,signal);signal.throwIfAborted();const metadata=parseOriginalMetadata(output,0);if(!metadata.hasVideo)throw new Error('Could not inspect original video');return {width:metadata.width,height:metadata.height,durationMs:metadata.duration*1000,startPTS:Number(/start:\s*(-?[\d.]+)/.exec(output)?.[1]??0)};}

interface JobDependencies {run?:(args:string[],signal:AbortSignal)=>Promise<unknown>;probe?:(file:string,signal:AbortSignal)=>Promise<VideoProbe>;freeBytes?:(dir:string)=>Promise<number>;}
export class ManagedMediaJobs {
 constructor(private registry:ManagedAssetRegistry,private queue:HeavyJobQueue,private deps:JobDependencies={}){}
 async ensureAudioStream(assetId:string,index:number,signal:AbortSignal,sourceChannelIndex?:number):Promise<string>{return this.queue.run(async()=>{if(!Number.isInteger(index)||index<0)throw new Error('Invalid audio stream index');if(sourceChannelIndex!==undefined&&(!Number.isInteger(sourceChannelIndex)||sourceChannelIndex<0||sourceChannelIndex>63))throw new Error('Invalid source audio channel');const variant=sourceChannelIndex===undefined?`audio-${index}`:`audio-${index}-channel-${sourceChannelIndex}`;const uri=`licketysplit-media://${assetId}/${variant}`;if(await this.registry.audioPreview(assetId,index,sourceChannelIndex))return uri;const src=await this.registry.resolve(assetId,'original');const asset=await this.registry.get(assetId);const channelTag=sourceChannelIndex===undefined?'':`-channel-${sourceChannelIndex}`;const base=path.join(this.registry.cacheDir,`${asset.identity.sha256}-audio-${index}${channelTag}-v1`);const partial=base+'.partial.m4a';try{const args=['-y','-i',src.path,'-map',`0:a:${index}`,'-vn'];if(sourceChannelIndex!==undefined)args.push('-af',`pan=mono|c0=c${sourceChannelIndex}`);args.push('-c:a','aac','-b:a','192k','-ar','48000','-ac',sourceChannelIndex===undefined?'2':'1','-movflags','+faststart',partial);await (this.deps.run??runFfmpeg)(args,signal);signal.throwIfAborted();await this.registry.trimDerivedCache((await fs.stat(partial)).size,assetId);const output=base+'.m4a';await fs.rename(partial,output);await this.registry.promoteAudioPreview(assetId,index,output,sourceChannelIndex);return uri;}finally{await fs.unlink(partial).catch(()=>{});}},signal);}
 async ensureProxy(assetId:string,_profile:ResourceProfile,signal:AbortSignal):Promise<ProxyReceipt>{return this.queue.run(async()=>{const cached=await this.registry.receipt(assetId);if(cached)return cached;const asset=await this.registry.get(assetId);const src=await this.registry.resolve(assetId,'original');const metadata=await (this.deps.probe??probeVideo)(src.path,signal);const {width,height}=proxyDimensions(metadata.width,metadata.height);const free=await (this.deps.freeBytes??(async dir=>{const s=await fs.statfs(dir);return Number(s.bavail)*Number(s.bsize);}))(this.registry.cacheDir);const need=Math.ceil(metadata.durationMs/1000*2_000_000/8)+1024**3;if(free<need)throw new Error(`Insufficient disk space in ${this.registry.cacheDir}: need ${need} bytes`);const base=path.join(this.registry.cacheDir,`${asset.identity.sha256}-540-v1`);const partial=base+'.partial.mp4';let effective='videotoolbox';try{const shared=['-y','-i',src.path,'-vf',`scale=${width}:${height}`,'-fps_mode','passthrough','-an','-movflags','+faststart'];try{await (this.deps.run??runFfmpeg)([...shared,'-c:v','h264_videotoolbox','-b:v','2000k',partial],signal);}catch(e){signal.throwIfAborted();effective='software';await (this.deps.run??runFfmpeg)([...shared,'-c:v','libx264','-preset','veryfast','-crf','28',partial],signal);}signal.throwIfAborted();await this.registry.trimDerivedCache((await fs.stat(partial)).size,assetId);const out=base+'-'+effective+'.mp4';await fs.rename(partial,out);const receipt:ProxyReceipt={assetId,sourceSha256:asset.identity.sha256,proxyUri:`licketysplit-media://${assetId}/proxy`,width,height,sourceStartPTS:metadata.startPTS,proxyStartPTS:0,durationMs:metadata.durationMs,version:1};await this.registry.promoteProxy(assetId,out,receipt);return receipt;}finally{await fs.unlink(partial).catch(()=>{});}},signal);}
}
