import {promises as fs} from 'node:fs';import path from 'node:path';import {createHash,randomUUID} from 'node:crypto';
import type {AnalysisSnapshot,PreparedAudio,DialogueSpan} from '../../../../../packages/core/src/lickety/types';import {NativeAudioAnalysis} from './audio-analysis';import {atomicJson,hashFile} from './asset-registry';
export interface AudioPreparationOptions {mode:'mixed'|'isolated-stereo';participants?:{channel:1|2;participantId:string}[];}
function wavHeader(frames:number,channels:number){const b=Buffer.alloc(44);const size=frames*channels*2;b.write('RIFF',0);b.writeUInt32LE(36+size,4);b.write('WAVEfmt ',8);b.writeUInt32LE(16,16);b.writeUInt16LE(1,20);b.writeUInt16LE(channels,22);b.writeUInt32LE(16000,24);b.writeUInt32LE(16000*channels*2,28);b.writeUInt16LE(channels*2,32);b.writeUInt16LE(16,34);b.write('data',36);b.writeUInt32LE(size,40);return b;}
function gainAt(span:DialogueSpan,localMs:number):number{const render=span.render;if(!render)return 1;let gain=render.volume;const seconds=localMs/1000;const points=render.automation?.volume;if(points?.length){let left=points[0],right=points.at(-1)!;for(let i=1;i<points.length;i++)if(points[i].time>=seconds){left=points[i-1];right=points[i];break;}const ratio=Math.max(0,Math.min(1,(seconds-left.time)/Math.max(.000001,right.time-left.time)));gain*=left.value+(right.value-left.value)*ratio;}if(render.fade?.fadeIn)gain*=Math.min(1,seconds/render.fade.fadeIn);if(render.fade?.fadeOut)gain*=Math.min(1,(render.clipDurationMs-localMs)/1000/render.fade.fadeOut);return Math.max(0,gain);}
export class PreparedAudioStore {
 constructor(readonly directory:string,private audio:NativeAudioAnalysis){}
 async prepare(snapshot:AnalysisSnapshot,options:AudioPreparationOptions,signal:AbortSignal):Promise<PreparedAudio>{signal.throwIfAborted();if(!snapshot.dialogue.length||snapshot.durationMs<=0)throw new Error('No dialogue to prepare');const channels=options.mode==='mixed'?1:2;const participants=options.participants??[];if(channels===2&&(participants.length!==2||new Set(participants.map(p=>p.channel)).size!==2||new Set(participants.map(p=>p.participantId)).size!==2))throw new Error('Isolated stereo requires two explicit participant/channel mappings');if(channels===2&&snapshot.dialogue.some(span=>!participants.some(p=>p.participantId===span.participantId||p.participantId===span.trackId)))throw new Error('Additional microphones require mixed diarization; none may be dropped');if(snapshot.dialogue.some(span=>span.render?.effects.some(e=>e.enabled)))throw new Error('Render and relink processed dialogue stems before transcribing audio with effects');await fs.mkdir(this.directory,{recursive:true});const key=createHash('sha256').update(snapshot.revisionHash+JSON.stringify(options)).digest('hex');const receiptFile=path.join(this.directory,key+'.json');try{const receipt=JSON.parse(await fs.readFile(receiptFile,'utf8')) as PreparedAudio;const file=await this.resolve(receipt);if(await hashFile(file,signal)===receipt.sha256)return receipt;}catch(e){signal.throwIfAborted();}
 const handleId=randomUUID();const file=path.join(this.directory,handleId+'.wav');const partial=file+'.tmp';const frames=Math.round(snapshot.durationMs*16);if(frames*channels*2>0xffffffff-36)throw new Error('Prepared audio exceeds WAV size; split this timeline');const output=await fs.open(partial,'wx',0o600);const hash=createHash('sha256');try{const header=wavHeader(frames,channels);await output.write(header);hash.update(header);
 for(let startMs=0;startMs<snapshot.durationMs;startMs+=10000){signal.throwIfAborted();const endMs=Math.min(snapshot.durationMs,startMs+10000);const count=Math.round(endMs*16)-Math.round(startMs*16);const mixed=Array.from({length:channels},()=>new Float32Array(count));for(const span of snapshot.dialogue){const overlapStart=Math.max(startMs,span.timelineStartMs),overlapEnd=Math.min(endMs,span.timelineEndMs);if(overlapEnd<=overlapStart)continue;const chunk=await this.audio.getNativeAudioWindow(span.assetId,span.render?.audioTrackIndex??0,span.sourceInMs+overlapStart-span.timelineStartMs,overlapEnd-overlapStart,signal,16000,1);const channel=channels===1?0:participants.find(p=>p.participantId===span.participantId||p.participantId===span.trackId)!.channel-1;const offset=Math.round((overlapStart-startMs)*16);for(let i=0;i<chunk.channels[0].length&&offset+i<count;i++)mixed[channel][offset+i]+=chunk.channels[0][i]*gainAt(span,overlapStart-span.timelineStartMs+i/16);}
 const bytes=Buffer.alloc(count*channels*2);for(let i=0;i<count;i++)for(let c=0;c<channels;c++)bytes.writeInt16LE(Math.round(Math.max(-1,Math.min(1,mixed[c][i]))*32767),(i*channels+c)*2);await output.write(bytes);hash.update(bytes);}
 await output.close();await fs.rename(partial,file);const receipt:PreparedAudio={handleId,snapshotHash:snapshot.revisionHash,sha256:hash.digest('hex'),sampleRate:16000,channels,durationMs:snapshot.durationMs};await atomicJson(path.join(this.directory,handleId+'.json'),receipt);await atomicJson(receiptFile,receipt);return receipt;}catch(e){await output.close().catch(()=>{});await fs.unlink(partial).catch(()=>{});throw e;}}
 async resolve(audio:PreparedAudio):Promise<string>{if(!/^[a-f0-9-]{36}$/.test(audio.handleId))throw new Error('Unknown managed audio handle');const receipt=JSON.parse(await fs.readFile(path.join(this.directory,audio.handleId+'.json'),'utf8')) as PreparedAudio;if(receipt.sha256!==audio.sha256||receipt.snapshotHash!==audio.snapshotHash||receipt.durationMs!==audio.durationMs||receipt.channels!==audio.channels||audio.sampleRate!==16000)throw new Error('Prepared audio identity mismatch');const file=path.join(this.directory,audio.handleId+'.wav');await fs.access(file);if(await hashFile(file)!==audio.sha256)throw new Error("Prepared audio content changed; prepare it again");return file;}
}
