import {materializeToTemp,getBridge} from "@openreel/core/media/native-media-bridge";
import type {MediaItem} from '@openreel/core';
import type {AssetIdentity,ProxyReceipt,RegisteredAsset} from '@openreel/core/lickety/types';
export function isProxyReceiptValid(receipt:ProxyReceipt,identity:AssetIdentity):boolean{return receipt.version===1&&receipt.assetId===identity.assetId&&receipt.sourceSha256===identity.sha256;}
export function desktopMediaAvailable(){return typeof window!=='undefined'&&window.openreel?.platform==='desktop'&&!!window.openreel.lickety;}
const registeredBlobs=new WeakMap<Blob,Promise<RegisteredAsset>>();
export async function registerDesktopMedia(item:MediaItem):Promise<RegisteredAsset>{const bridge=window.openreel?.lickety;if(!bridge)throw new Error('Desktop media unavailable');const file=item.blob??await item.fileHandle?.getFile();if(file&&registeredBlobs.has(file))return registeredBlobs.get(file)!;const register=async()=>{if(file instanceof File)return bridge.registerFile(item.id,file);if(item.nativeSource)return item.nativeSource;const existing=await bridge.findAsset(item.id);if(existing)return existing;if(!file)throw new Error('Relink original media before preparation');try{return await bridge.registerFile(item.id,file);}catch(e){const native=getBridge();if(!native)throw e;return bridge.registerPath(item.id,await materializeToTemp(native,file));}};const result=register();if(file){registeredBlobs.set(file,result);result.catch(()=>registeredBlobs.delete(file));}return result;}

export async function resolveDesktopMedia(item:MediaItem,purpose:'preview'|'export'):Promise<string>{const bridge=window.openreel?.lickety;if(!bridge)throw new Error('Desktop media unavailable');const asset=item.nativeSource??await registerDesktopMedia(item);const original=await bridge.resolve(asset.identity.assetId,'original');if(purpose==='export'||item.type!=='video')return original;const profile=await bridge.resourceProfile();if(profile.lowMemory&&(Math.max(item.metadata.width,item.metadata.height)>960||Math.min(item.metadata.width,item.metadata.height)>540)){const receipt=await bridge.ensureProxy(asset.identity.assetId);if(!isProxyReceiptValid(receipt,asset.identity))throw new Error('Preview proxy changed; retry preparation');return receipt.proxyUri;}return original;}
