import {create} from 'zustand';import {persist} from 'zustand/middleware';import type {AnalysisSnapshot,JobState,NarrativeProposal,Project} from '@openreel/core';import {useProjectStore} from './project-store';import {snapshotDialogue,prepareAnalysisAudio,waitForTranscript,type TranscriptionOptions} from '../services/lickety/transcription';
interface JobRef {jobId:string;snapshot:AnalysisSnapshot;state:JobState;error?:string;}
interface WorkflowState {jobs:Record<string,JobRef>;busy:boolean;error?:string;proposal?:NarrativeProposal;proposalSource?:Project;proposalRevision?:string;start(project:Project,options:TranscriptionOptions):Promise<void>;resume(project:Project):Promise<void>;cancel(projectId:string):Promise<void>;setProposal(proposal:NarrativeProposal,source:Project,revision:string):void;}
const controllers=new Map<string,AbortController>();
export const useLicketyWorkflowStore=create<WorkflowState>()(persist((set,get)=>({jobs:{},busy:false,error:undefined,
 setProposal:(proposal,source,revision)=>set({proposal,proposalSource:source,proposalRevision:revision}),
 start:async(project,options)=>{if(get().busy)return;const bridge=window.openreel?.lickety;if(!bridge)throw new Error('Desktop transcript unavailable');const c=new AbortController();controllers.set(project.id,c);set({busy:true,error:undefined});try{const snapshot=await snapshotDialogue(project);const audio=await prepareAnalysisAudio(snapshot,options,c.signal);const {jobId}=await bridge.startTranscription({audio,snapshot,...options,confirmationId:crypto.randomUUID()});set(state=>({jobs:{...state.jobs,[project.id]:{jobId,snapshot,state:'submitted'}}}));await get().resume(project);}catch(error){set({error:error instanceof Error?error.message:'Transcript failed'});}finally{set({busy:false});controllers.delete(project.id);}},
 resume:async(project)=>{const bridge=window.openreel?.lickety;const job=get().jobs[project.id];if(!bridge||!job)return;const c=controllers.get(project.id)??new AbortController();controllers.set(project.id,c);set({busy:true,error:undefined});try{await bridge.resumeTranscription(job.jobId);const doc=await waitForTranscript(job.jobId,c.signal,state=>set(current=>({jobs:{...current.jobs,[project.id]:{...job,state:state as JobState}}})));const current=useProjectStore.getState().project;const tracks=new Set(job.snapshot.dialogue.map(span=>span.trackId));const currentInput={...current,timeline:{...current.timeline,tracks:current.timeline.tracks.map(t=>({...t,role:tracks.has(t.id)?"dialogue" as const:t.role==="dialogue"?"general" as const:t.role}))}};if(current.id!==project.id||(await snapshotDialogue(currentInput)).revisionHash!==job.snapshot.revisionHash)throw new Error('Dialogue changed while transcribing. The provider result is saved; return to the submitted edit to use it.');const prior=current.lickety;useProjectStore.setState({project:{...current,timeline:{...currentInput.timeline,markers:current.timeline.markers.filter(m=>!m.id.startsWith('lickety-cue:'))},modifiedAt:Date.now(),lickety:{schemaVersion:1,snapshot:job.snapshot,transcript:doc,words:doc.words.map(w=>({occurrenceId:w.id,sourceWordId:w.sourceWordId??w.id,text:w.text,startMs:w.startMs,endMs:w.endMs,speaker:w.speaker,channel:w.channel})),...(prior?.podcastSetup?{podcastSetup:prior.podcastSetup}:{}),...(prior?.podcastAssembly?{podcastAssembly:prior.podcastAssembly}:{})}}});set(state=>({proposal:undefined,proposalSource:undefined,proposalRevision:undefined,jobs:{...state.jobs,[project.id]:{...job,state:'completed'}}}));}catch(error){const message=error instanceof Error?error.message:'Transcript recovery failed';const result=await bridge.getTranscription(job.jobId).catch(()=>undefined);set(state=>({error:message,jobs:{...state.jobs,[project.id]:{...job,state:result?.state??job.state,error:message}}}));}finally{set({busy:false});controllers.delete(project.id);}},
 cancel:async(projectId)=>{controllers.get(projectId)?.abort(new Error('Cancelled'));const ref=get().jobs[projectId];if(ref)await window.openreel?.lickety?.cancelTranscription(ref.jobId);set({busy:false});},
}),{name:'licketysplit-local-workflow-jobs-v1',partialize:state=>({jobs:state.jobs})}));
